TP1_PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_stats.urls as app_stats
import app_update_status.urls as app_update_status
import add_friend.urls as add_friend
import app_profile.urls as app_profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stats/', include(app_stats,namespace='app_stats')),
    url(r'^update_status/', include(app_update_status,namespace='app_update_status')),
    url(r'^friend/', include(add_friend,namespace='add_friend')),
    url(r'^profile/', include(app_profile,namespace='app_profile')),    
    url(r'^$', RedirectView.as_view(url='/update_status/', permanent=True),name='index')
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_update_status/urls.py
from django.conf.urls import url
from .views import index, status_post

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_post', status_post, name='add_post'),
    ]

add_friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length = 27)
	url = models.URLField()
	date = models.DateTimeField(auto_now_add=True)

app_profile/models.py
from django.db import models

# Create your models here.
class profileuser(models.Model):
    photo = models.TextField(default="https://image.ibb.co/nOFEFb/glasses.png")
    name = models.CharField(max_length=30)
    birthday = models.DateField()
    gender = models.CharField(max_length=10)
    expertise = models.CharField(max_length=50)
    description = models.TextField()
    email = models.EmailField()

app_stats/models.py
from django.db import models

# Create your models here.

app_update_status/models.py
from django.db import models

class Post(models.Model):
    post = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
    	return self.post

add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'This field is required',
        'invalid': 'Please fill in your friend\'s herokuapp link',
    }
    name_attrs = {
        'class': 'form-control',
        'placeholder':'What is your friend\'s name?'
    }

    url_attrs = {
        'class': 'form-control',
        'placeholder':'What is your friend\'s herokuapp link?'
    }


    name = forms.CharField(label='Name', required=True, max_length=27, empty_value='Anonymous', 
        widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='URL', required=True, empty_value='Anonymous',
        widget=forms.URLInput(attrs=url_attrs))
    

app_update_status/forms.py
from django import forms

class Post_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    attrs = {
        'class': 'form-control'
    }
    post = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

# Create your views here.
response = {}
def index(request):
	html = 'add_friend/add_friend.html'
	response['friend_form'] = Friend_Form
	friend = Friend.objects.all()
	response['friend'] = friend
	return render(request,html,response)
def add_friend(request):
	form = Friend_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
		response['url'] = request.POST['url'] if request.POST['url'] != "" else "Anonymous"
		friend = Friend(name=form.cleaned_data['name'], url=form.cleaned_data['url'])
		friend.save()
	else:
		response['form'] = form
	html ='add_friend/add_friend.html'
	friend = Friend.objects.all()
	response['friend'] = friend
	return render(request,html,response)

app_profile/views.py
from django.shortcuts import render
from .models import profileuser

# Create your views here.
def index(request):
    try:
        profile = profileuser.objects.get(id=1)
        split = profile.expertise.split(',')
        response = {'title':'Profile', 'profile': profile, 'split':split}
        return render(request, 'profile.html', response)
    except profileuser.DoesNotExist:
        response = {'title':'Profile', 'profile': 'error', 'split':'error'}
        return render(request, 'profile.html', response)

app_stats/views.py
from django.shortcuts import render
from app_profile.models import profileuser
from add_friend.models import Friend
from app_update_status.models import Post


def index(request):
    response = {}

    profile = profileuser.objects.get(pk=1) 
    friendCount = Friend.objects.all().count()
    feedCount = Post.objects.all().count()
    
    html = 'stats.html'
    response["profile"] = profile
    response["friends"] = friendCount
    response["feed"] = feedCount

    qs = Post.objects.order_by('-created_date')
    if(len(qs) > 0):
        latest_post = qs[0]
    else:
        latest_post = None

    response['latest_post'] = latest_post

    return render(request, html, response)

app_update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Post
from .forms import Post_Form
from app_profile.models import profileuser

response = {}

def index(request):
    # profile = profileuser.objects.get(pk=1)
    # profile.save()
    response['post_form'] = Post_Form
    # response['profile'] = profile
    html = 'app_update_status/app_update_status.html'
    post = Post.objects.all()
    response['post'] = post
    return render(request, html, response)
    
def status_post(request):
    form = Post_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
            response['post'] = request.POST['post']
            postingan = Post(post=response['post'])
            postingan.save()
            return HttpResponseRedirect('/update_status/')

add_friend/templates/add_friend/add_friend.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Friends</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
	
</head>
<body class="friend-body">
<section class="media container">
	<img class="title" src="{% static 'image/maintitle.png' %}" alt="Generic placeholder image" style="width:450px;height:200px;">
</section>
<hr/>
<section name="input-friend" id="input-friend">
    <div class="container">
    <br>
    <br>
        <form id="form" method="POST" action="{% url 'add_friend:add_friend' %}">
            <h2>Connect with Your Friend</h2>
            {% csrf_token %}
            {{ friend_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Add Friend">
        </form>
    </div>
</section>

<section name="friend" id="friend">
   	<div class="container">
    <br>
   	<h2 class="friend-title">Friends</h2>
      <div class="card-body">
        {% for i in friend %}
        <div class="card" style="width: 20rem;">
          <center><img class="card-img-top" src="{% static 'image/avatar.png' %}" alt="Card image cap" style="width: 60px; height: 60px;"></center>
            <center><h4 id="name-friend">{{i.name}}</h4></center>
            <center><p class="added-friend"> Added on {{i.date}}</p></center>
            <center><a href="{{ i.url }}"> {{i.url}} </a></td></center>
            <br>
          </div>
        {% endfor %}
      </div>
	</div>
</section>

<!-- Print errors if any -->
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <!-- List all previous status -->
    <div class="container stasuses">
        {% for i in status reversed %}
            <div class="flex-item">
                <h5> {{ i.user.name }} </h5>
                {{ i.friend }} <br/>
                <sub> {{ i.date }} </sub>
            </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

app_profile/templates/profile.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}
<style>
.kotak{
        background-color: white;
        width: 500px;
        margin: auto;
        box-shadow: 5px 5px 5px #888888;
    }
.expert{
    border: 2px solid #F299C2;
    padding: 5px;
    padding-left: 10px;
    padding-right: 10px;
    border-radius: 10px;
    margin-right: 10px;
 background-color:#F299C2;
}

.img-circle {
        border-radius: 50%;
        width: 200px;
        height: 200px;
}

#expert{
  transition-duration: 0.5s;
}
#expert:hover{
  background-color: white;
}
#editbutton{
  width: 10vw; 
  display:block; 
  margin:0 auto;
  border: #F299C2 solid 2px;
  text-align: center;
  border-radius: 20px;
  background-color: #F299C2;
  color: white;
  -webkit-transition-duration: 0.4s;
  transition-duration: 0.4s;
}

#editbutton:hover{
  border: #F299C2 solid 2px;
  text-align: center;
  border-radius: 20px;
  background-color: white;
  color: #F299C2;
}

</style>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<section name="profile" style="margin-top:100px; margin-bottom:50px">
<link href="https://fonts.googleapis.com/css?family=Alegreya+Sans" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
    <div class="kotak">
        <div class="container">
            <br/>
    	    <h2 style="text-align: center; margin-top: 20px; font-size: 35px; font-family: Didact Gothic">P R O F I L E</h2>
        </div>
        <div style= "margin-top: 35px" class="profilecenter">
            <div>
                <img class="img-circle" style="display:block; margin:auto;" src={{profile.photo}} border="0" /></a>
                <br/>
                <h2 style="text-align:center; font-family: Alegreya Sans"><b>{{profile.name}}</b></h2>
                <p style="text-align:center; font-family: Alegreya Sans"><i>{{profile.description}}</i></p>
            </div>
        </div>

        <div class="container">
                <!-- Trigger the modal with a button -->
                <button class="btn btn-lg btn-block btn-info" id="editbutton" data-toggle="modal" data-target="#myModal" style="font-size-adjust: 30px">Edit</button>
                <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title" style="align-items: center; font-family: Alegreya Sans">Edit Profile</h4>
                      </div>
                      <div class="modal-body">
                        <form>
                          <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="name" value="{{profile.name}}">
                            </div>
                          </div>
                          <div class="form-group row">
                            <label for="description" class="col-sm-2 col-form-label">Description</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="description" value="{{profile.description}}">
                            </div>
                          </div>
                          <div class="form-group row">
                            <label for="birthday" class="col-sm-2 col-form-label">Birthdate</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="birthdate" value="{{profile.birthday}}">
                            </div>
                          </div>
                          <div class="form-group row">
                            <label for="gender" class="col-sm-2 col-form-label">Gender</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="gender" value="{{profile.gender}}">
                            </div>
                          </div>
                            <div class="form-group row">
                              <label for="email" class="col-sm-2 col-form-label">Email</label>
                              <div class="col-sm-10">
                                <input type="email" class="form-control" id="email" value="{{profile.email}}">
                              </div>
                            </div>
                          <div class="form-group row">
                            <label for="expertise" class="col-sm-2 col-form-label">Expertise</label>
                            <div class="col-sm-10">
                              <input type="expertise" class="form-control" id="expertise" value="{{profile.expertise}}">
                            </div>
                          </div>
                        <div class="form-group row">
                          <label for="photo" class="col-sm-2 col-form-label">Photo Image URL</label>
                          <div class="col-sm-10">
                            <input type="link" class="form-control" id="link" value="{{profile.photo}}">
                          </div>
                      </div>
                          <div class="form-group row" style="align-self: center">
                            <div class="col-sm-10">
                              <button type="submit" class="btn btn-lg btn-block btn-info" id="submitbutton" style="float:center">Save</button>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>


        <div class="biodata">
            <table align="center" style="text-align: left; padding: 10px; font-family: Alegreya Sans; font-size: 18px">
                <td style= "font-weight: bold;" class="subject">Birthday</td><td class="value" style=" padding: 10px">{{profile.birthday}}</td>
                <tr><td class="subject" ><b>Gender</b></td><td class="value" style=" padding: 10px">{{profile.gender}}</td></tr>
                <tr><td class="subject" ><b>Email</b></td><td class="value" style=" padding: 10px">{{profile.email}}</td></tr>
            </table>
            <br/>
            <p style= "text-align: center; font-family: Alegreya Sans; font-weight: bolder; font-size: 20px"><b>Expertise</b></p>
            <table align= "center" style= "text-align: center; font-family: Alegreya Sans; font-weight: bolder;">
                <tr>{% for ii in split %}<td class="value" style="text-align: center;"><span style= "padding: 7px; font-color:#FFFFFF" id="expert" class="expert"><b>{{ii}}</b></span>{% endfor %}</td></tr>
            </table> 
            <br/>
        </div>
    </div>
</section>


<br><br>

{% endblock %}

app_stats/templates/stats.html
{% extends "base.html" %}
{% block content %}

<div class="stats-container">
	<h1 style="text-align: center"> Stats </h1>  	
	<div class="profile">
    	<h2> <image style = "border-radius: 50%; margin-left: 100px; float: left;" width=200px height=200px align="middle" src={{profile.photo}}> 
       	</h2>
	</div>  
	<section name="basic-stats" id="basic-stats">
		<h2 class="profile-name"> {{profile.name}} </h2> 
		<h5 class="profile-item"> Friend : {{friends}} </h2> 
    	<h5 class="profile-item"> Feed : {{feed}} </h2> 
	</section>
    

    <section name="latest-post" id="latest-post">
		<div class="container-post">
			<h4>Latest Post</h4>
			{% if latest_post is not None %}
				<p>{{ latest_post.post }}</p><br>
				<p>{{ latest_post.created_date }}</p><br>
			{% else %}
				<p>This user hasn't posted anything yet :(</p>
			{% endif %}
	</section>

</div>
{% endblock %}

app_update_status/templates/app_update_status/app_update_status.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container">
	<style>
		#form {
			resize:none
			width:100%
		}
		img {
			float:left
		}

	</style>
	<section name="form">
		<h2>Update Status</h2>
        <form id="form" method="POST" action="{% url 'app_update_status:add_post' %}">
            {% csrf_token %}
            {{ post_form }}
            <br>
            <button type="Post" class="btn btn-default">Post</button>
        </form>
    </section>
    <hr>
	<body>
		{% for data in post reversed %}
			<div class="profile">
				<img src={{profile.photo}} width=50px height=50px></img>
				<h4>{{profile.name}}</h4>
			</div>
			<p id="postingan">{{data.post}}</p>
			<h5 id="tanggal">{{data.created_date}}</h5>
			<hr>
		{%endfor%}
	</body>
</div>
	
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Ling In</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
</head>
<style>
	body {
		/*margin:0px;*/
		background-color: #c6e9f4;
		background-repeat : none;
	}

	.container-post {
		background-color: white;
		margin: 10px 200px 10px 200px;
		padding: 20px;
	}

	#basic-stats {
		padding-bottom: 100px;
		margin-top: 50px;
		/*padding-bottom: 500px;*/
	}

	.profile-item {
		color:#565656;
	}

	.container-post {
		box-shadow: 10px 10px 5px #888888;
	}
/*	.home {
		padding: 0px 100px 0px 100px
	}

	.stats-container {
		margin-left: 50px;
		margin-right: 50px; 
		height: 100%
	}
	.topnav {
		overflow: hidden;
		background-color: #474747;
		box-shadow: 0px 0px 0px red inset;
		padding-right: 100px;
		padding-left: 100px
	}

	.topnav a {
		display: block;
		float: right;
		color: white;
		text-align: center;
		font-size: 15px;
		padding: 10px 15px;
		text-decoration: none;
		border-left: 1px #686868 solid;
		border-right: 1px #686868 solid;
		transition : box-shadow 0.2s;
	}

	.topnav p {
		display: block;
		float: left;
		padding: 0px;
	}
	.profile-item{
		margin-left: 20px
	}

	.topnav a:hover {
		box-shadow: 0px -4px 0px red inset;		
	}

	.topnav a.first-item {
		border-right: 2px #686868 solid;
	}

	.topnav a.last-item {
		border-left: 2px solid #686868;
	}*/
</style>
<body>
	<!-- <div class="container">
		<div class="topnav">
			<a class="first-item" href="/home/"> Home </a>
			<a href="#profile"> Profile </a>
			<a href="#friend"> Friend </a>
			<a href="#status"> Status </a>
			<a class="last-item" href="/stats/"> Stats </a>	
		</div>			
	</div> -->

	<div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#" style="font-family: Cookie; font-size: 25px ">Ling In</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item" >
                <a class="nav-link" href="/profile/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/friend/">Friend</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/stats/">Stats</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/update_status/">Status</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>

	{% block content %}
	{% endblock %}	
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</html>